all:
 gcc challenge.c -o chall -static
 strip chall                                                                                                                                                                                             
